env:
  es6: true
  browser: true
  commonjs: true
  jest: true
  node: true

extends: ["airbnb", "prettier", "plugin:node/recommended"]

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 6
  sourceType: module

plugins: ["prettier"]

settings:
  react:
    version: "16"

rules:
  prettier/prettier: "error"
  react/jsx-filename-extension: [0]
  no-unused-vars: "warn",
  no-console: "off",
  func-names: "off",
  no-process-exit: "off",
  object-shorthand: "off",
  class-methods-use-this: "off"